project:
  output-dir: "_site"

website:
  title: ""
  navbar:
    background: dark
    left:
      - href: index.html
        text: Home
      - href: AboutMe/index.qmd
        text: About Me
      - href: Resume/index.qmd
        text: Resume
      - href: ContactMe/index.qmd
        text: Contact Me
      - href: Projects/index.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



