project:
  type: website

website:
  title: ""
  navbar:
    background: dark
    left:
      - href: index.html
        text: Home
      - href: syllabus/index.qmd
        text: Syllabus
      - href: schedule/index.qmd
        text: Schedule
      - href: resources/index.qmd
        text: Resources
      - href: contributors/index.qmd
        text: Contributors

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



