---
title: "Syllabus"
layout: full
toc: true
---

# CMPSC 302: Web Design

This page contains information about the Web Design course at Allegheny College, including the course objectives and outcomes, and its policies.

## Instructor

Dr. Janyl Jumadinova

Office Location: Alden Hall 110

Email: jjumadinova@allegheny.edu

[Office Hours](https://janyljumadinova.com/schedule)

## Description

Credits: 4

An introduction to the principles and applications of web design with an emphasis on understanding intercultural perspectives that arise during the design, implementation, and maintenance of responsive, modern web sites. Participating in hands-on activities that often require teamwork, students learn the computational methods needed to create websites that are useful to people from different cultures and nationalities. Students also investigate approaches to developing efficient, accessible, and aesthetically pleasing web sites that adhere to the international standards set by the World Wide Web Consortium. During a weekly laboratory session students use industry-grade web development technologies to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.

Prerequisite: CMPSC 104.

Distribution Requirements: IP, SP.

## Learning Outcomes

### Course Learning Outcomes

1. Apply HTML, CSS, Markdown, and basic Javascript to develop well-structured, responsive World Wide Web Consortium (W3C) standards-compliant web sites.
2. Evaluate and implement web accessibility measures consistent with the Web Content Accessibility Guidelines (WCAG) version 2 specification.
3. Design front-end user experiences using accepted web design patterns, methods, and information structures.
4. Identify and use strategies of successful visual rhetoric for the web.
5. Compare and select web technologies such as static site generators or frameworks as appropriate candidates for building web sites.

### Distribution Requirements

**IP: International & Intercultural Perspectives (IP).** An understanding of International & Intercultural Perspectives means awareness that culture provides the interpretive lens for action in the world, and that one’s particular culture is itself one of many cultures of the world. It includes the ability to recognize and understand the results of cultural difference wherever they are found, as well as an awareness of the norms of one’s own culture or those of other cultures.

- **Learning Outcome**: Students who successfully complete this requirement will demonstrate an understanding of cultural complexity and difference.

**SP: Scientific Process & Knowledge (SP).** Courses involving Scientific Process & Knowledge aim to convey an understanding of what is known or can be known about the natural world; apply scientific reasoning towards the analysis and synthesis of scientific information; and create scientifically literate citizens who can engage productively in problem solving.

- **Learning Outcome:** Students who successfully complete this requirement will demonstrate an understanding of the nature, approaches, and domain of scientific inquiry.

Course learning outcomes 1, 2, 3 and 4 satisfy IP learning outcome. 
All course learning outcomes satisfy SP requirement.

## Policies

### Communication

Course website and Discord are the main digital channels used in this course for communication. Students are responsible for regularly checking these platforms to ensure that the important messages are not being missed.

### Department Policies

In this course, we will follow [department's policies](https://www.cis.allegheny.edu/teaching/policies/) regarding attendance, late assignment submissions, and AI use. Two weeks of missed attendance implies six missed class sessions. Non-participation in a class/lab activity will result in a missed attendance mark.

### Grading Contract

This course emphasizes process and growth. Your grade reflects not just the completion of assignments but also your engagement with the material, your participation, and your effort to produce creative, thoughtful, authentic work. 

Besides quizzes, you will never see an actual letter grade from me on an assignment. Instead, I will provide formative feedback following a detailed rubric developed for each assignment. Does that mean you can't get anything _wrong_? No, of course not. You'll still have plenty of opportunity and encouragement to fail. All this means is that `failure != "F"`. The only thing that leads to failure here is inauthentic effort.

At the end of the semester, I have to give you a grade, and for that we will follow this contract. Given that this course relies on process, this contract shapes itself around the idea that students engage and participate at a meaningful level.

### Final Letter Grade Contract

| Final Letter Grade | Software Portfolio (3 Projects) | Quizzes (~5 total) | Technical Challenges | IP Presentation |
|---------------------|---------------------------------|-------------------|-----------------------|----------------------------------------|
| A                   | All completed                  | Average ≥ 90%    | 100% completed        | 1 completed                            |
| A-                  | All completed                  | Average ≥ 85%    | 95% completed         | 1 completed                            |
| B+                  | All completed                  | Average ≥ 80%    | 90% completed         | 1 completed                            |
| B                   | All completed                  | Average ≥ 75%    | 85% completed         | 1 completed                            |
| B-                  | All completed                  | Average ≥ 70%    | 80% completed         | 1 completed                            |
| C+                  | All completed                  | Average ≥ 65%    | 75% completed         | 1 completed                            |
| C                   | All completed                  | Average ≥ 60%    | 70% completed         | 1 completed                            |
| C-                  | 2 completed                    | Average ≥ 55%    | 65% completed         | 0 completed                            |
| D                   | 2 completed                    | Average ≥ 60%    | 60% completed         | 0 completed                            |

#### A note about assignment types

##### Quizzes

A closed-note quiz will be given on average every two weeks that assesses conceptual understanding of the topics covered up to that point.

##### International & Intercultural Perspectives Presentation

One presentation, given in a small team, that demonstrates International & Intercultural Perspectives of web design. 

##### Technical Challenges

Small weekly assignments that provide exploration of the tools and technologies at hand. Graded on a Pass/Fail basis, where "Pass" is defined as meeting the basic requirements outlined in each challenge's rubric. 

##### Web Portfolio

There are three required projects: course website, personal website, community project (introduced in this order). Course web and community web projects are completed in teams. Personal website project is completed individually. Projects are graded on a Pass/Fail basis. All three software portfolio projects have scaffolded tasks and deadlines throughout the semester, and require engagement in a standard software engineering process.

#### `Incomplete` and `Ignored` Assignments

- **Incomplete Assignments:** Assignments that fail to meet basic requirements. Revisions may be requested.  
- **Ignored Assignments:** Assignments with no meaningful submission will receive no credit.

[Tokens](https://forms.gle/MbV2iXiojrezyRE48) may be used for these assignments as described in the department's policy with the exception of the final submission of the web portfolio. A token must be requested *at most one week after* the assignment deadline.

## Allegheny College Policy and Awareness Statements

### Statement of Community

>  Allegheny students and employees are committed to creating an inclusive, respectful and safe residential learning community that will actively confront and challenge racism, sexism, heterosexism, religious bigotry, and other forms of harassment and discrimination. We encourage individual growth by promoting a free exchange of ideas in a setting that values diversity, trust and equality. So that the right of all to participate in a shared learning experience is upheld, Allegheny affirms its commitment to the principles of freedom of speech and inquiry, while at the same time fostering responsibility and accountability in the exercise of these freedoms.

### Academic Integrity

Allegheny College has a student-run Honor Code designed to promote individual responsibility and integrity in academic affairs. Each student pledges the following: “I hereby recognize and pledge to fulfill my responsibilities, as defined in the Honor Code, and to maintain the integrity of both myself and the College community as a whole.” Your professor will educate you about the meaning of academic integrity in this course, which may be different in some respects from other courses in which you are enrolled. Please ask the professor if you have questions. Please see [academic honor program's website](https://sites.allegheny.edu/studentsuccess/academic-honor-program/) for more details.

### Midterm Grades

Midterm grades will be submitted for all students in this course by Monday, March 17, but will not appear on academic transcripts. By giving you an early indication of your performance so far, midterm grades offer an opportunity to make adjustments, if necessary, before the end of the term. While midterm grades are primarily focused on first and second-year students, upper-level students may also receive them in some courses. This feedback is a key part of our commitment to supporting your academic journey. 

### Seeking assistance

#### Assistance with course concepts

Students who struggle to understand knowledge and skills defined in this course are encouraged to seek assistance from the instructor. To meet with me, consult my available office hours (above) and make an appointment. See above for my office hours or go to [this schedule for Technical Leaders' office hours](https://www.cs.allegheny.edu/teaching/technicalleaders/).

#### Educational Accommodations (prepared by SASS)

Students with disabilities who believe they may need accommodations in this class are encouraged to contact Student Accessibility and Support Services (SASS) at (814) 332-2898.  Student Accessibility and Support Services is located in Pelletier Library.  Please do this as soon as possible to ensure that such accommodations are implemented in a timely fashion. Please see [student accessibility's website](https://sites.allegheny.edu/studentaccessibility/) for more details.

#### Religious Observance (prepared by SRL)

If you need to miss class or reschedule a final examination due to a religious observance, please speak to the professor well in advance to make arrangements. Please see [religious holidays' website](https://sites.allegheny.edu/religiouslife/religious-holy-days) for more details.

#### Academic Alerts (prepared by MCSS)

Allegheny College uses an Academic Alert system to send progress notices to the class deans in the Maytum Center for Student Success (MCSS). The progress notices are not punitive. They are an opportunity to connect you with your class dean who can offer additional support and suggest resources if you need assistance. These notices may encourage faculty advisors, coaches (for student-athletes), or other support staff to provide outreach to you as well.

#### Mental Health and Wellness (prepared by Wellness in Student Life)

As a college student, there may be times when personal stressors, struggles, and/or traumas interfere with your academic performance and/or negatively impact your daily life. Allegheny College recognizes that mental health is an important piece of the holistic human experience, and that this experience influences your academic success. We encourage students to prioritize their mental well-being by seeking services and support as needed.

Keep in mind, course deadlines, absences, and accommodations for mental health are subject to the course policies and expectations that are set within this syllabus. Students are encouraged to communicate with their professors as soon as possible regarding their needs and seek support if their mental health impacts their academic performance or daily life. When you find yourself struggling emotionally, remember that there are supports available, and you are not alone.

Students who are in need of mental health support can access multiple resources to receive support.  The 98.6 CampusCare app provides physical and behavioral health consultation and supports free of charge 24/7 via telehealth for any actively enrolled student who downloads and signs up with their smartphone.  Allegheny College has also partnered with ECPS (Edinboro Counseling and Psychological Services) to provide in-person therapy on campus. The ECPS partnership with Allegheny College delivers holistic mental health services to the Allegheny College student community through brief individual counseling, and crisis support. 

Students may request services from ECPS by calling (814) 332-4368 or by emailing the Wellness Case Manager at `wellness@allegheny.edu`.
If you or someone you know is experiencing a mental health emergency, please call the 988 Suicide and Crisis Lifeline, Public Safety (814-332-3357), or 911. All of these urgent resources are available 24/7/365.  When in doubt, reach out.

#### Gator Success Grants

The [Gator Success Grant](https://sites.allegheny.edu/gator-success-grants/) program is designed to provide students with additional financial assistance to offset the total cost of college attendance and to encourage successful on-time degree completion. Currently enrolled students who have an unanticipated need are invited to apply. Grants are usually from a few hundred to a few thousand dollars, depending on the request and the student's need. Please direct questions to `studentsuccess@allegheny.edu`.

#### Writing and Speaking Consultants (prepared by the Directors of Writing and Speaking) 

Experienced peer writing and speaking consultants in the Maytum Center for Student Success help writers and speakers make academically responsible choices and determine strategies for effective communication at any stage in the writing or speaking process, for assignments in any discipline, or for writing and speaking situations unrelated to coursework (e.g., personal statements, cover letters, interviews, conference presentations). Both appointments and drop-in sessions are available. To view the hours of operation, and to make an appointment, visit the [Maytum Center for Student Success website](https://sites.allegheny.edu/maytum-center-student-success/writing-speech/).

#### Gator Days and Scholar Symposium (prepared by MCSS and URSCA) 

In each semester, we have one Gator Day set aside for programming, with no classes. Fall Gator Day is held on the first Tuesday in November (coinciding with election day). Spring Gator Day is held on a Monday in early April. These all-college programming days  feature programs and workshops that highlight educational opportunities at Allegheny, that prepare students for life after graduation, and that help to create a greater sense of campus community. Additionally, in the Spring, during the Richard J Cook – Teresa M Lahti Scholars Symposium (the day immediately after classes end and before exams begin), we gather to celebrate student research, scholarship, and creative activities on campus. We 

#### Class Deans (prepared by MCSS) 

The [Office of Class Deans](https://allegheny.edu/academics/student-success/support-from-class-deans/) in Pelletier Library serves as a place for students to begin seeking assistance and answers to their questions related to college life. If you have a question and don’t know who to ask – ask a class dean. If you want advice – talk to a class dean. Aacha Gregg is the First Year Class Dean, Amy Stearns is the Second Year Class Dean / Director of Transfer Advising, and Carene Shipley is the Third/Fourth Year Class Dean. Dom Turner is the Associate Dean for Diversity, Equity, and Inclusion, located in Schultz Hall. Please contact them individually or through `studentsuccess@allegheny.edu`.

#### Recording Policy (prepared by Campus Life and Community Standards Committee)

In remote teaching and learning contexts, there is an understanding that instructors (including faculty, coaches, staff, and facilitators) have the right to record class and discussion proceedings.  All other participants must request permission of the instructor in advance before making any additional recordings.  An instructor's pre-recorded material, including lectures and class notes, may not be shared with anyone outside of the course's current enrollment without the consent of the instructor. Similarly, under no circumstances may a recording, still, screenshot, picture, or any other media of any sort be altered or circulated by anyone outside of its original intent. No content may be distributed outside the circle of participants without the consent of all who appear or are heard. The college community is reminded of Allegheny College's Recording Policy, outlined in 9.8 of the Faculty Handbook, as well as Allegheny's Statement of Community. Violations will be referred to the Student Conduct system.  Classes may also be recorded if approved as an educational accommodation through the Student Accessibility and Support Services. Faculty are further reminded that recordings of class activities are educational records protected under FERPA. While students do not have a right to be anonymous in a class in which they are enrolled, they have the legal right to be anonymous to third parties. Please direct questions about FERPA to the Registrar.

#### Harassment, Discrimination, and Sexual Misconduct Reporting (prepared by the Title IX Coordinator)

Allegheny College is committed to providing a workplace and educational environment that is free from all forms of harassment, discrimination, and sexual misconduct. The College expressly prohibits discrimination and harassment on the basis of race, color, national origin, ethnicity, sex, sexual orientation, gender, gender identity, gender expression, age, religion, and disability. Allegheny College prohibits sex-based harassment, sexual violence, intimate partner violence, and stalking regardless of the gender, gender identity, gender expression, or sexual orientation of the individuals involved in any education program or activity that it operates, as required by Title IX, including admission and employment.

Allegheny College adheres to all federal, state, and local civil rights laws prohibiting discrimination in employment and education. The College does not discriminate in its admissions practices, in its employment practices, or in its educational programs or activities. Allegheny College also prohibits retaliation against any person participating in good faith in any discrimination investigation or complaint process internal or external to the institution; for bringing a complaint of discrimination or harassment or for assisting someone with such a complaint.

Allegheny College is required to respond promptly and effectively, utilizing a fair, transparent, and reliable process, when they have knowledge of conduct that reasonably may constitute sex discrimination in its program, and must take steps to prevent the recurrence of discrimination and remedy its effects, the college must communicate their policies and procedures to all students, employees, and other participants in their programs and must monitor and address barriers to reporting instances of sex discrimination.

Allegheny College employees must notify their Title IX Coordinator when they have information that may reasonably rise to the level of sex discrimination, so long as the employee is not a confidential employee, as defined on page 3 of this policy. All employees must be trained upon hiring and annually thereafter on (i) the College’s obligation to address sex discrimination, (ii) the scope of conduct that constitutes sex discrimination under Title IX, including sex-based harassment, and (iii) all duties of employees upon receipt of a report of sex discrimination, including to provide the reporting individual with contact information for the Title IX Coordinator and information about how to report sex discrimination under Title IX.

Joe Hall, Interim Title IX Coordinator
814-332-3085 (direct line), `jhall@allegheny.edu`, Campus Center 310A

You can access support and resources even if you do not want to take any further action. The College respects your right to file or not file a formal complaint. The Title IX Coordinator must take action only in situations that pose a serious threat of harm to you or the community. 

_Notice that Faculty are Responsible Employees with Mandatory Reporting Obligations:_

Unless specifically identified otherwise by policy, all faculty, staff, and administrators of Allegheny College are considered mandated reporters and are required to notify the College’s Title IX Coordinator of any incident of discrimination and harassment disclosed to them, or known to them, involving a member of the campus community. Mandated reporting helps to ensure that individuals who are experiencing or have experienced discrimination or harassment are connected to the full range of resources and options afforded to them. 

If you are in need of support or advocacy and wish to discuss such matters confidentially, you are invited to consult any of the resources listed below. Unlike other College employees, the options below are confidential and are exempt from mandatory reporting obligations to the Title IX Coordinator. These resources are free and include both internal and external options.

__On Campus Options:__
- Meadville Medical Center @ Winslow - (814-332-4355) - Walk-ins welcome - Open from M-F 10am-3pm (last patient check-in at 2:30pm) while classes are in session.
- ECPS partnership with Allegheny College (Edinboro Counseling and Psychological Services) - (814) 332-4368 - Please call to schedule an appointment.
- 98point6 CampusCare - Allegheny students can download the app for iOS or Android smartphones, confirm their cell phone number, and complete their profile to receive services.  This physical/behavioral telehealth service is free of charge for all actively enrolled students at Allegheny College.
- Wellness in Student Life - `wellness@allegheny.edu` - (814) 332-2782 

__Off Campus Options:__

- [Meadville Medical Center Emergency Room](https://sites.allegheny.edu/title-ix/resources/), 751 Liberty Street – (814) 333-5500
- [Meadville Crisis Line](https://sites.allegheny.edu/title-ix/resources/), (814) 724-2732
- [Women’s Services](https://www.google.com/url?q=https://www.womensservicesinc.com/&sa=D&source=docs&ust=1724791366323234&usg=AOvVaw10Y2eKAZSPd53YUPxQqdml), Inc., (814) 724-4637 (office)
- 24-hour Hotlines: (814) 333-9766  or (888) 881-0189

If you would like more information on the College's Harassment, Discrimination and Sexual Misconduct Policy click [here](https://sites.allegheny.edu/title-ix/).
[Resources | Title IX | Allegheny College](https://sites.allegheny.edu/title-ix/resources/)
